-- AlterTable
ALTER TABLE "ATHL" ADD COLUMN     "closeTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "highTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lowTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
